services:
  postgres-db:
    image: postgres:15
    container_name: postgres-db
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: fiap
      POSTGRES_PASSWORD: senhaFiap
      POSTGRES_DB: database
    volumes:
#      - ./data/postgres:/var/lib/postgresql/data
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    container_name: app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: postgres
      SPRING_DATASOURCE_USERNAME: fiap
      SPRING_DATASOURCE_PASSWORD: senhaFiap
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/database
      depends_on:
        postgres-db

volumes:
  postgres-data:
