name: CI - Feature

on:
  push:
    branches:
      - develop
      - main

jobs:
  build-docker:
    name: Build and PR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ vars.DOCKER_USERNAME }}/gerenciador-trafego-fiap:${{ github.ref_name }}-${{ github.sha }}

  deploy:
    name: Deploy into Azure App Service
    runs-on: ubuntu-latest
    needs: build-docker

    steps:
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        id: deploy-azure-app
        with:
          app-name: ${{ secrets.AZURE_APP_NAME }}
          publish-profile: ${{ secrets.AZURE_APP_PUBLISH_PROFILE }}
          slot-name: Production
          images: ${{ vars.DOCKER_USERNAME }}/gerenciador-trafego-fiap:${{ github.ref_name }}-${{ github.sha }}
