name: CI - Feature

on:
  push:
    branches:
      - "feature**"

# permissions:
  # contents: write
  # pull-requests: write

jobs:
  build-and-pr:
    name: Build and PR
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: 'maven'
      
      - name: Build
        run: mvn clean package -DskipTests
      
      - name: List build artifacts
        run: ls -lrt target
      
      - name: Upload build artifacts
        id: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/*.jar
      
      - name: Criar PR automático para develop
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: 'Merge automático da feature'
          title: 'Merge automático da feature'
          body: 'CI passou com sucesso e o PR foi aberto automaticamente para develop'
          base: develop
          branch: develop
          token: ${{ secrets.GITHUB_TOKEN }}
