name: CI - Feature

on:
  push:
    branches:
      - "feature**"

permissions: write-all

jobs:
  build-and-pr:
    name: Build and PR
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: 'maven'

      - name: Build
        run: mvn clean package -DskipTests
      
      - name: List build files
        run: ls -lrt target

      - name: Run tests
        run: mvn test
      
      - name: Login to Docker Hub 
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACESS_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ vars.DOCKER_USERNAME }}/${{ github.repository }}:feature-${{ github.ref_name }}
            ${{ vars.DOCKER_USERNAME }}/${{ github.repository }}:feature-${{ github.sha }}

